# Generated by Django 4.2.1 on 2023-06-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginpage", "0004_ebayproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="amazonproduct",
            name="link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ebayproduct",
            name="link",
            field=models.CharField(default="", max_length=255),
        ),
    ]
